language: python
python:
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"
# command to install dependencies
install: "pip install -e . -r requirements-test.txt"
# command to run tests
script: nosetests peppertext/ && flake8 --config tox.ini peppertext/
